---
- name: Play1
  hosts: all
  become: yes
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"

    - name: Unconditionally reboot the machine with all defaults
      reboot:
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"
